---
title: "GoM_trial_cleanup"
author: "WH MacKenzie"
date: "2023-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(RPostgres)
library(data.table)
require(dplyr)
require(DataExplorer)
require(uuid)
# 
# 
# load_GOM_psites <- function() {
#   con <- dbConnect(RPostgres::Postgres(),dbname = 'reforest_app',
#                    host = '159.203.56.62',
#                    port = 5432, # or any other port specified by your DBA
#                    user = 'postgres',
#                    password = 'BECisGOD2023')
#   
#   psites <- data.table(dbGetQuery(con,"select * from planting_info"))
#   psites
# }
# psites <- load_GOM_psites()

con <- dbConnect(RPostgres::Postgres(),dbname = 'reforest_app',
                 host = '159.203.56.62',
                 port = 5432, # or any other port specified by your DBA
                 user = 'postgres',
                 password = 'BECisGOD2023')
```

## Download data off server

```{r import data}
psites <- data.table(dbGetQuery(con,"select * from planting_info"))
planter <- data.table(dbGetQuery(con,"select * from planter_info"))
trials <- data.table(dbGetQuery(con,"select * from trial_info"))
plantedby <- left_join(psites,planter, by = c("planter_id" = "_id")) %>% select(planter_id.y) %>% count(planter_id.y)
fwrite(plantedby, "./outputs/GoM_planted_by_planter.csv")
fwrite(planter, "./outputs/GoM_planters.csv")
dbGetQuery(con,"select distinct species from planting_info")

psites[planter, PlanterName := i.planter_id, on = c(planter_id = "_id")]
#psites <- psites[!PlanterName %in% c("KSD","Coco","kdaust"),]
fwrite(psites, "./outputs/PlantingSites_GOM.csv")
fwrite(planter, "./outputs/Planters_GOM.csv")
fwrite(trials, "./outputs/Trials_GOM.csv")

```

### Summarize
```{r}
plantedby <- full_join(psites,planter, by = c("planter_id" = "_id"))# %>% select(planter_id.y) %>% count(planter_id.y)
planter2 <- plantedby %>% group_by(planter_id, planter_id.y) %>% summarize(countplanter = n())
fwrite(planter2, "./outputs/CountPlantings_by_planter.csv")
num_trials_planters <- left_join(planter, psites, by = c("_id" = "planter_id")) %>% select(`_id`, plantation_id) %>% group_by(`_id`) %>% summarise(non_na_count = sum(!is.na(plantation_id))) %>% left_join(planter)
fwrite(num_trials_planters, "./outputs/CountPlantings_by_plantertable.csv")

trialsby <- full_join(psites,trials, by = c("planter_id" = "_id"))
trials2 <- trialsby %>% group_by(trial_id.x) %>% summarize(countplantations = n())
species_seedlot <- psites %>% count(species, seedlot)
fwrite(species_seedlot, "./outputs/CountSppxSeedlot.csv")

```

```{r trial summaries, echo=FALSE}
DataExplorer::create_report(psites)
```


