---
title: "Lw_Understorey"
author: "Will MacKenzie"
date: "2023-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(sf)
require(data.table)
require(tidyverse)
require(terra)
require(fasterize)
library(readr)
library(rmapshaper)
require(tictoc)
require(ggplot2)
require(forcats)
#library(BiodiversityR) # also loads vegan
require(DataExplorer)
library(readxl)
library(ggsci)
library(ggrepel)
library(ggforce)
require(Hmisc)
require(colorspace)
#source("./_functions/doc_theme_pem.R")

```
## Study of EP0976 understorey vegetation with a focus on Larch differences.

```{r import veg}
veg <- fread("./data/Ep0976_understory.csv") %>% mutate(species = toupper(Species)) 
totals <- c("TREE", "SHRUB", "HERB", "MOSS", "TOTAL" )
veg_tot <- veg %>% filter(species %in% totals)
veg_spp <- veg %>% filter(!species %in% totals)
```
## Veg cover by canopy
```{r}
not.plot = c("TREE", "TOTAL")
veg_tot2 <- veg_tot %>% filter(!species %in% not.plot) %>% mutate(species = recode(species, "MOSS" = "0Moss", "HERB" = "1Herb", "SHRUB" = "3Shrub"))
ggplot(veg_tot2, aes(x=block, y=PC, fill = species ))+
  geom_violin(scale = "width", draw_quantiles = c(.25,.5,.75), position = position_dodge(width = 0.9))+
  #geom_boxplot(aes(fill=species))+
  geom_point(position=position_dodge(width=.75),aes(group=species))+
  #geom_dotplot(binaxis = 'y', stackdir = 'center')+
  coord_flip()+
  facet_grid(cols = vars(Site))
ggsave("./graphics/Violin.pdf")
 require(mltools) 
veg_corr <- veg_tot %>% select(plot_label, block, species, PC) %>% mutate(block = as.factor(block)) %>% pivot_wider(id_cols = c(plot_label, block), names_from = species, values_from = PC) %>% select (-TOTAL) %>% mutate_all(~replace_na(.,0)) 
### add species as one-hot variable
veg_corr2 <- one_hot(as.data.table(veg_corr )) %>% select(-1)
## plot correlation matrix with one hot categories
library(ggcorrplot)
corr.diag <- model.matrix(~0+., data=veg_corr2) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag=FALSE, type="lower", lab=TRUE, lab_size=2)
corr.diag
ggsave("./graphics/TotalsCorrelation.pdf")


library("PerformanceAnalytics")
## shows correlation, histogram, and statistical values
pdf(file="./graphics/TotalsCorrelation2.pdf")
chart.Correlation(veg_corr2, histogram=TRUE, pch=19)
dev.off()

# tot.cor = cor(veg_corr[-1], method = c("spearman"))
# tot.rcorr = Hmisc::rcorr(as.matrix(veg_corr[-1]))
# tot.rcorr

```



## understorey composition

```{r pressure, echo=FALSE}
require(labdsv)
library(vegan)
trees <- c("ABIELAS", "PINUCON", "THUJPLI", "PINUCON", "PICEENE", "LARIOCC", "PSEUMEN", "BETUPAP", "TSUGHET")
site.select = c("BB","BC","DC")
veg_anal <- veg_spp %>% filter(Site_label %in% site.select) %>% select(plot_label, species, PC) %>% mutate(PC = as.numeric(PC)) %>% filter(!species %in% trees) %>%  drop_na()
veg.site <- veg_spp %>% select(plot_label, everything(), -Plot, -Date, -Layer, -Species, -PC, -species) %>% distinct() %>% as_tibble() %>% arrange(plot_label)
veg_matrix <- matrify(veg_anal)

#veg_matrix <- pivot_wider(veg_anal, names_from = species, values_from = PC) %>% replace_na(0)
veg.dist <-  proxy::dist(veg_matrix, method = "jaccard")
veg.1=hclust(veg.dist,method="ward.D")
plot(veg.1)
#rect.hclust(veg.1,4)
veg.scale=cmdscale(veg.dist,eig=T)
veg.scale$GOF

as_tibble(veg.scale$points) %>%
  rownames_to_column("site") %>% 
    mutate(group=veg.site$block) %>%
  ggplot(aes(x=V1,y=V2,colour = group, label=site))+
    geom_point()+geom_text_repel()+coord_fixed()
```


```{r NMDS, echo=FALSE}
# lifeform.matrix = veg_matrix
# envdat = veg.site 
# group = "Site_label"

get_ord <- function(lifeform.matrix, envdat, group) {
lifeform.dist <- proxy::dist(lifeform.matrix, method = "jaccard")#, binary = F
  ord <- ade4::dudi.pco(lifeform.dist, nf = 3, scannf = F)
  coords <- ord$li %>% select(1,2)%>% rownames_to_column ("plot")  
  groups = envdat %>% rename("plot" = 1)
  groups <- groups[,c("plot", group)]
 coords <- left_join(coords, groups) %>% rename("group" = 4)
 #coords$SiteSeries <- as.character( coords$SiteSeries)
  ordplot <- ggplot(coords, aes(A1, A2)) +
       geom_mark_hull(aes(fill = group, label = group))+ 
 
     #geom_text(data=,aes(x=NMDS1,y=NMDS2,label=species),alpha=0.5) +  # add the species labels
  geom_point(aes(shape=group),colour = "black", size=1) + # add the point markers,,colour=SiteSeries
  geom_text(aes(label=plot),size=2,vjust=-0.5) +   # add the site labels
scale_color_discrete_sequential(palette = "Viridis", rev = FALSE)+
scale_fill_discrete_sequential(palette = "Viridis", rev = FALSE) +
#   coord_equal() +
  theme_no_axes()+
    ggtitle(group)+
    guides(shape = F, label = F)+
theme(legend.position = "none", plot.title = element_text(size = 14))
  plot(ordplot)
}

get_ord(veg_matrix, veg.site, group = "Site")
ggsave("./graphics/ordination_by_trialsite.pdf")
```


```{r pressure, echo=FALSE}
h=veg.1$height
h
d=tibble(clusters=53:2,height=h)


dist <- dsvdis(veg_matrix, index = "bray/curtis")
nmds <- nmds(dist)
plot(nmds, ids = TRUE)

as_tibble(dune.scale$points) %>% 
  rownames_to_column("site") %>% 
  mutate(farming=dune.env$Management) %>% 
  ggplot(aes(x=V1,y=V2,colour=farming,label=site))+
    geom_point()+geom_text_repel()+coord_fixed()


#Get MDS stats
sol<- metaMDS(veg_matrix,distance = "bray", k = 2, trymax = 50)
ord <- ordiplot(sol, choices = c(1,2))
type <- sites.long(ord, env.dat = veg.site)
plot.new()
ord<-ordiellipse(sol, labels ,display = "sites", kind ="sd", conf = 0.95, label = T)
dev.off()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
